name: Update README activity

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_MSG: "chore: update activity in README"
